version: "3.9"
services:
  databus:
    build: .
    ports:
      - "8088:8080"
    depends_on:
      - "gitlab"
      - "virtuoso"
  gitlab:
    image: "gitlab/gitlab-ce:13.8.8-ce.0"
    environment:
      GITLAB_OMNIBUS_CONFIG: "gitlab_rails['initial_root_password'] = 'password'"
    ports:
      - "8880:80"
  virtuoso:
    image: "tenforce/virtuoso:1.3.2-virtuoso7.2.5.1"
    environment:
      DBA_PASSWORD: "everyoneknows"
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    ports:
      - "8890:8890"