version: "3.0"
services:
  gstore:
    build: .
    ports:
      - "3002:3002"
    environment:
      GSTORE_JETTY_PORT: 3002
    volumes:
      - ./databus/git:/gstore/git
      - ./databus/logs:/gstore/logs
  gstore-virtuoso:
    image: "openlink/virtuoso-opensource-7"
    # todo remove this port exposure for production
    ports:
      - "3003:8890"
    environment:
    # note:
    # these params only work first time to create ini
    # to change after edit virtuoso.ini
      SPARQL_UPDATE: "true"
      DBA_PASSWORD: "everyoneknows"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    volumes:
      - ./databus/virtuoso:/database
    healthcheck:
      test: echo 'select 1;' | isql 1111 dba $$DBA_PASSWORD
      interval: 5s
      retries: 10
      timeout: 10s
  after-virtouso-startup:
    image: "openlink/virtuoso-opensource-7"
    environment:
      DBA_PASS: "everyoneknows"
    depends_on:
      gstore-virtuoso:
        condition: service_healthy
    entrypoint: /bin/bash
    command: >
      -c "
        echo 'grant SPARQL_LOAD_SERVICE_DATA to \"SPARQL\";' | isql gstore-virtuoso:1111 dba $$DBA_PASS &&
        echo 'grant SPARQL_SPONGE to \"SPARQL\";' | isql gstore-virtuoso:1111 dba $$DBA_PASS &&
        echo success
      "