version: "3.0"
services:
  gstore:
    build: .
    ports:
      - "3002:3002"
    environment:
      GSTORE_JETTY_PORT: 3002
    volumes:
      - ./databus/git:/gstore/git
      - ./databus/logs:/gstore/logs
    depends_on:
      after-virtouso-startup:
        condition: service_completed_successfully
  gstore-virtuoso:
    image: "openlink/virtuoso-opensource-7"
    # todo remove this port exposure for production
    ports:
      - "3003:8890"
    environment:
    # note:
    # these params only work first time to create ini
    # to change after edit virtuoso.ini
      SPARQL_UPDATE: "true"
      DBA_PASSWORD: "everyoneknows"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    volumes:
      - ./databus/virtuoso:/database
  after-virtouso-startup:
    image: "openlink/virtuoso-opensource-7"
    environment:
      DBA_PASS: "everyoneknows"
    depends_on:
      - "gstore-virtuoso"
    entrypoint: /bin/bash
    command: >
      -c "
        echo start &&
        for i in 1 2 3 4 5; do bash -c 'cat < /dev/null > /dev/tcp/gstore-virtuoso/1111' && break || sleep 10; done &&
        echo 'grant SPARQL_LOAD_SERVICE_DATA to \"SPARQL\";' | isql gstore-virtuoso:1111 dba $$DBA_PASS &&
        echo 'grant SPARQL_SPONGE to \"SPARQL\";' | isql gstore-virtuoso:1111 dba $$DBA_PASS &&
        echo success
      "