version: "3.9"
services:
  databus:
    depends_on:
      - "gitlab"
      - "gstore-virtuoso"
  gitlab:
    image: "gitlab/gitlab-ce:13.8.8-ce.0"
    environment:
      GITLAB_OMNIBUS_CONFIG: "gitlab_rails['initial_root_password'] = 'password'"
    ports:
      - "8880:80"
