version: "3.0"
services:
  gstore:
    build: .
    ports:
      - "3002:3002"
    depends_on:
      - "gstore-virtuoso"
  gstore-virtuoso:
    image: "openlink/virtuoso-opensource-7"
    environment:
    # note: 
    # these params only work first time to create ini
    # to change after edit virtuoso.ini
      VIRT_HTTPSERVER_SERVERPORT: "$VIRT_HTTPSERVER_SERVERPORT"
      SPARQL_UPDATE: "true"
      DBA_PASSWORD: "${VIRT_PASS}"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    ports:
      - "${VIRT_HTTPSERVER_SERVERPORT}:${VIRT_HTTPSERVER_SERVERPORT}"
    volumes:
      - ./databus/virtuoso:/database
