version: "3.0"
services:
  gstore:
    build: .
    ports:
      - "3002:3002"
    volumes:
      - ./databus/git:/databus/git
      - ./databus/logs:/databus/logs
    depends_on:
      - "gstore-virtuoso"
  gstore-virtuoso:
    image: "openlink/virtuoso-opensource-7"
    environment:
    # note: 
    # these params only work first time to create ini
    # to change after edit virtuoso.ini
      VIRT_HTTPSERVER_SERVERPORT: "3003"
      SPARQL_UPDATE: "true"
      DBA_PASSWORD: "everyoneknows"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    ports:
      - "3003:3003"
    volumes:
      - ./databus/virtuoso:/database
