version: "3.9"
services:
  databus:
    build: .
    ports:
      - "8088:80"
    depends_on:
      - "virtuoso"
  virtuoso:
    image: "tenforce/virtuoso:1.3.2-virtuoso7.2.5.1"
    environment:
      DBA_PASSWORD: "everyoneknows"
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"