version: "3.9"
services:
  databus:
    build: .
    ports:
      - "8088:8080"
    depends_on:
      - "virtuoso"
  virtuoso:
    image: "openlink/virtuoso-opensource-7"
    environment:
      DBA_PASSWORD: "everyoneknows"
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"