version: "3.0"
services:
  gstore:
    build: .
    ports:
      - "3002:3002"
    environment:
      GSTORE_JETTY_PORT: 3002
    volumes:
      - ./databus/git:/gstore/git
      - ./databus/logs:/gstore/logs
    depends_on:
      - "gstore-virtuoso"
  gstore-virtuoso:
    image: "openlink/virtuoso-opensource-7"
    # todo remove this port exposure for production
    ports:
      - "3003:8890"
    environment:
    # note:
    # these params only work first time to create ini
    # to change after edit virtuoso.ini
      SPARQL_UPDATE: "true"
      DBA_PASSWORD: "everyoneknows"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    volumes:
      - ./databus/virtuoso:/database
