swagger: "2.0"
info:
  description: "This is the DbPedia databus web-api draft."
  version: "1.0.0"
  title: "Databus API"
basePath: "/databus"
schemes:
  - "https"
paths:
  /shacl/validate:
    post:
      summary: "Validate dataid with shacl"
      description: ""
      operationId: "shaclValidate"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      parameters:
        - in: formData
          name: graph
          type: string
          required: true
          format: binary
          description: "dataid contents (jsonld expected)"
        - in: formData
          name: shacl
          type: string
          required: true
          format: binary
          description: "contents of a shacl file"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
  /file/save:
    post:
      summary: "Save file"
      description: ""
      operationId: "saveFile"
      consumes:
        - "application/ld+json"
      produces:
        - "application/json"
      parameters:
        - in: query
          name: username
          type: string
          required: true
        - in: query
          name: path
          type: string
          required: true
        - in: body
          name: body
          description: "Turtle or JSONLD."
          required: true
          schema:
            type: string
            format: binary
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
  /file/delete:
    post:
      summary: "Delete file"
      description: ""
      operationId: "deleteFile"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: query
          name: username
          type: string
          required: true
        - in: query
          name: path
          type: string
          required: true
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
  /file/read:
    get:
      summary: "Get file"
      description: ""
      operationId: "getFile"
      produces:
        - "application/ld+json"
        - "text/turtle"
      parameters:
        - in: query
          name: username
          type: string
          required: true
        - in: query
          name: path
          type: string
          required: true
      responses:
        "200":
          description: "A file"
          schema:
            type: string
            format: binary
  /api/dataid/tractate:
    post:
      summary: "Returns a subgraph of dataid for signing"
      description: ""
      operationId: "dataidSubgraph"
      consumes:
        - "application/json"
      produces:
        - "text/plain"
      parameters:
        - in: "body"
          name: "body"
          description: "Returns dataid file tractate"
          required: true
          schema:
            type: string
            format: binary
      responses:
        "200":
          description: "successful operation, here we can just use Base64 encoded body"
          schema:
            type: string
definitions:
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
