swagger: "2.0"
info:
  description: "This is the DbPedia databus web-api draft."
  version: "1.0.0"
  title: "Databus API"
basePath: "/databus"
schemes:
  - "https"
paths:
  /{username}/{groupId}:
    put:
      summary: "Create group"
      description: ""
      operationId: "createGroup"
      consumes:
        - "application/ld+json"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: group
          type: string
          required: true
          description: Group name
        - in: path
          name: username
          type: string
          required: true
        - in: "body"
          name: "body"
          description: "Turtle or JSONLD with group meta."
          required: true
          schema:
            type: string
            format: binary
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
    delete:
      summary: "Delete group"
      description: ""
      operationId: "deleteGroup"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: group
          type: string
          required: true
          description: Group name
        - in: path
          name: username
          type: string
          required: true
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
    get:
      summary: "Get group meta"
      description: ""
      operationId: "getGroup"
      produces:
        - "application/ld+json"
        - "text/turtle"
      parameters:
        - in: path
          name: group
          type: string
          required: true
          description: Group name
        - in: path
          name: username
          type: string
          required: true
      responses:
        "200":
          description: "A group description file"
          schema:
            type: string
            format: binary
  /{username}/{group}/{artifact}/{version}:
    put:
      summary: "Create version"
      description: ""
      operationId: "createVersion"
      consumes:
        - "application/ld+json"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: version
          type: string
          required: true
          description: Version name
        - in: path
          name: group
          type: string
          required: true
          description: Version name
        - in: path
          name: username
          type: string
          required: true
          description: Version name
        - in: path
          name: artifact
          type: string
          required: true
          description: Version name
        - in: "body"
          name: "body"
          description: "Turtle or JSONLD with version meta."
          required: true
          schema:
            type: string
            format: binary
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
    delete:
      summary: "Delete version"
      description: ""
      operationId: "deleteVersion"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: version
          type: string
          required: true
          description: Version name
        - in: path
          name: group
          type: string
          required: true
          description: Version name
        - in: path
          name: username
          type: string
          required: true
          description: Version name
        - in: path
          name: artifact
          type: string
          required: true
          description: Version name
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
    get:
      summary: "Get version meta"
      description: ""
      operationId: "getVersion"
      produces:
        - "application/ld+json"
        - "text/turtle"
      parameters:
        - in: path
          name: version
          type: string
          required: true
          description: Version name
        - in: path
          name: group
          type: string
          required: true
          description: Version name
        - in: path
          name: username
          type: string
          required: true
          description: Version name
        - in: path
          name: artifact
          type: string
          required: true
          description: Version name
      responses:
        "200":
          description: "A dataid file"
          schema:
            type: string
            format: binary
  /api/dataid/subgraph/:
    post:
      summary: "Returns a subgraph of dataid for signing"
      description: ""
      operationId: "dataidSubgraph"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Returns dataid file body subgraph. Here we can just use Base64 encoded body"
          required: true
          schema:
            type: string
            format: binary
      responses:
        "200":
          description: "successful operation, here we can just use Base64 encoded body"
          schema:
            type: string
  /api/dataid/subgraph/hash/:
    post:
      summary: "Calculates hash of the subgraph of the dataid file for signing"
      description: "Just for convenience"
      operationId: "dataidSubgraphHash"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Dataid subgraph data"
          required: true
          schema:
            type: string
            format: binary
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/DataIdSignatureMeta"
definitions:
  DataIdSignatureMeta:
    type: "object"
    description: "may be needed to add some more details"
    properties:
      hash:
        type: "string"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
